Repository AppQuality/unguess-react, pull requests merged in 2025-05, with the labels that each got.

#1310 UN-1343-accordion
  src/common/components/inviteUsers/campaignSettings.tsx
  src/common/components/inviteUsers/projectSettings.tsx
  src/common/components/inviteUsers/styled.tsx
  src/common/components/inviteUsers/userItem.tsx
  src/pages/Video/components/Observation.tsx
Labels: enhancement

#1309 UN-1264: Fix plans view more behaviour
  src/locales/en/translation.json
  src/pages/Dashboard/project-items/Plans.tsx
  src/pages/Dashboard/project-items/index.tsx
Labels: bug, e2e

#1301 UN-1342 feat: Refactor user state access and add Navigation component with header
  src/features/navigation/Navigation/NavigationHeader.tsx
  src/features/navigation/Navigation/NavigationProfileModal.tsx
  src/features/navigation/Navigation/index.tsx
  src/hooks/useActiveWorkspace.ts
  src/hooks/useActiveWorkspaceProjects.ts
  src/hooks/useFeatureFlag.ts
  src/hooks/useGTMevent.ts
  src/pages/Dashboard/index.tsx
  src/pages/Video/index.tsx
Labels: refactor

#1321 Fix delete project
  src/locales/en/translation.json
  src/pages/Dashboard/Modals/DeleteProjectModal.tsx
  src/pages/Dashboard/headerContent.tsx
  src/pages/Dashboard/projectPageHeader.tsx
Labels: bug
