Repository AppQuality/unguess-react, pull requests merged in 2025-04, with the labels that each got.

#1247 refactor(plan): restructure DeleteModuleConfirmationModal footer with FooterItem components
  src/pages/Plan/modals/SendRequestModal.tsx
  src/pages/Plan/modules/Tasks/parts/modal/DeleteTaskConfirmationModal.tsx
  src/pages/Plan/modules/Touchpoints/parts/modal/DeleteTouchpointConfirmationModal.tsx
  src/pages/Plan/modules/modal/DeleteModuleConfirmationModal.tsx
Labels: enhancement, e2e

#1251 feat(validation): add required task and touchpoint error messages
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/modules/Tasks/hooks/index.ts
  src/pages/Plan/modules/Tasks/parts/TasksList.tsx
  src/pages/Plan/modules/Touchpoints/hooks/index.ts
  src/pages/Plan/modules/Touchpoints/parts/TouchpointsList.tsx
Labels: enhancement, e2e

#1252 Un 1130 task url validation
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/modules/Tasks/hooks/index.ts
  src/pages/Plan/modules/Tasks/parts/TaskItem.tsx
  src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx
  src/pages/Plan/modules/Tasks/utils/getIconFromTask.tsx
Labels: enhancement, e2e

#1255 Updated Copy for Enhanced End-to-End flow
  src/locales/en/translation.json
Labels: good first issue

#1267 UN-1044 fix: add title and translations for aside navigation modules
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/navigation/aside/NavBody.tsx
Labels: bug, e2e

#1268 UN-1141 enhance request quotation flow with error handling and loading state indication
  src/features/modules/useRequestQuotation.ts
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/modals/SendRequestModal.tsx
Labels: enhancement

#1265 UN-1037 removed info message and icon from targetsize
  src/pages/Plan/modules/TargetSize.tsx
Labels: bug, e2e

#1266 UN-1042 fix: remove numbering from module titles in aside navigation
  src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx
  src/pages/Plan/navigation/aside/NavBody.tsx
  src/pages/Plan/navigation/aside/NavItem.tsx
Labels: bug, e2e

#1271 fix: enhance navigation for invalid plan IDs and handle query errors
  src/pages/Plan/index.tsx
Labels: bug, e2e

#1278 Fixes to aside nav
  src/pages/Plan/ModulesList.tsx
  src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx
  src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointItemNav.tsx
  src/pages/Plan/navigation/aside/NavItem.tsx
Labels: bug, e2e

#1286 UN-1036: fix closed sidebar on "templates" click
  src/features/navigation/Navigation.tsx
Labels: bug, e2e

#1282 UN-1048: update scroll spacer height calculation in ModulesList component
  src/pages/Plan/ModulesList.tsx
  src/pages/Plan/modules/Tasks/parts/nav/TaskItemNav.tsx
  src/pages/Plan/modules/Touchpoints/parts/nav/TouchpointItemNav.tsx
Labels: bug, e2e

#1281 UN-1047: add missing subtitles to aside navigation
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/navigation/aside/NavItem.tsx
  src/pages/Plan/utils/getSubtitleFromModuleType.tsx
Labels: bug, e2e

#1294 UN-1208: Fix archive page view
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Dashboard/Project.tsx
  src/pages/Dashboard/project-items/index.tsx
  tests/api/workspaces/wid/projects/pid/_get/200_Archived_Empty_Project.json
  tests/api/workspaces/wid/projects/pid/_get/200_Archived_Project.json
  tests/e2e/archive.spec.ts
  tests/fixtures/pages/Archive.ts
Labels: bug, e2e

#1293 UN-1018: Fix close accordion clicking delete
  src/pages/Plan/modules/AdditionalTarget.tsx
  src/pages/Plan/modules/Age.tsx
  src/pages/Plan/modules/Browser.tsx
  src/pages/Plan/modules/Gender.tsx
  src/pages/Plan/modules/Goal.tsx
  src/pages/Plan/modules/InstructionsNote.tsx
  src/pages/Plan/modules/Language.tsx
  src/pages/Plan/modules/Literacy.tsx
  src/pages/Plan/modules/OutOfScope.tsx
  src/pages/Plan/modules/SetupNote.tsx
  src/pages/Plan/modules/TargetNote.tsx
  src/pages/Plan/modules/TargetSize.tsx
  src/pages/Plan/modules/Tasks/parts/TaskItem.tsx
  src/pages/Plan/modules/Tasks/parts/TasksList.tsx
  src/pages/Plan/modules/Touchpoints/parts/TouchpointItem.tsx
  src/pages/Plan/modules/Touchpoints/parts/TouchpointsList.tsx
Labels: bug, e2e

#1299 UN-1010: Add delete plan feature
  package.json
  src/locales/en/translation.json
  src/locales/it/translation.json
  src/pages/Plan/Controls.tsx
  src/pages/Plan/modals/DeletePlanModal.tsx
  tests/e2e/plan/draft.spec.ts
  tests/fixtures/pages/Plan.ts
  yarn.lock
Labels: feature, e2e
